name: tools
publish_to: none

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  file: ^6.1.2
  git: ^2.0.0
  path: ^1.8.0
  simons_pub_uploader:
    version: ^1.1.0
    hosted: https://simonbinder.eu

dev_dependencies:
  lints: ^1.0.0
