name: docs
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  built_site:
  docsy:

dev_dependencies:
  build_runner: ^2.0.3
  build_web_compilers: ^3.0.0

dependency_overrides:
  built_site:
    path: ../built_site
  docsy:
    path: ../themes/docsy
